# src/config.py

# Đường dẫn file dữ liệu
RELATIONS_PATH = 'data/Relations_group.json'
CONCEPTS_PATH = 'data/Concepts.json'

# Mapping từ tên tiếng Việt/thông dụng sang ID trong JSON (Entity Linking)
ENTITY_MAPPING = {
    # Chòm sao
    "aries": "Aries",
    "taurus": "Taurus",
    "gemini": "Gemini",
    "cancer": "Cancer",
    "leo": "Leo",
    "virgo": "Virgo",
    "libra": "Libra",
    "scorpio": "Scorpius", "scorpius": "Scorpius",
    "sagittarius": "Sagittarius",
    "capricorn": "Capricorn",
    "aquarius": "Aquarius",
    "pisces": "Pisces",

    # Các ngôi sao (nếu người dùng hỏi tên sao trực tiếp)
    "hamal": "Hamal", "aldebaran": "Aldebaran", "pollux": "Pollux", "al tarf": "Al Tarf", "regulus": "Regulus", "spica": "Spica", 
    "zubeneschamali": "Zubeneschamali", "antares": "Antares", "kaus australis": "Kaus Australis", "deneb algedi": "Deneb Algedi",
    "sadalsuud": "Sadalsuud", "eta piscium": "Eta Piscium",

    # Các thực thể thần thoại
    "hercules": "Hercules", "artemis": "Artemis", "zeus": "Zeus", "aphrodite": "Aphrodite", "eros": "Eros", 
    "astraea": "Astraea", "gaia": "Gaia", "cừu vàng": "Con Cừu Vàng", "chiron": "Chiron", "aegipan": "Aegipan", 
    "ganymede": "Ganymede", "ichthyes": "Ichthyes", "bò mộng": "Bò Mộng Cretan", "europa": "Europa", "nemean": "Sư Tử Nemean",
    "castor": "Castor", "pollux": "Pollux", "leda": "Leda", "hera": "Hera", "carcinus": "Carcinus",
    "cán cân công lý": "Cán cân Công lý", "themis": "Themis", "orion": "Orion", "kheiron": "Kheiron", "pan": "Aigipan",
    "typhon": "Typhon", "phrixus": "Phrixus", "helle": "Helle",

    # Các nguyên tố
    "lửa": "Lửa", "đất": "Đất", "khí": "Khí", "nước": "Nước",

    # Các hành tinh
    "sao thuỷ": "Sao Thuỷ", "sao kim": "Sao Kim", "trái đất": "Trái Đất",
    "mặt trăng": "Mặt Trăng", "sao hoả": "Sao Hoả", "sao mộc": "Sao Mộc", "sao thổ": "Sao Thổ",
    "sao thiên vương": "Sao Thiên Vương", "sao hải vương": "Sao Hải Vương", "sao diêm vương": "Sao Diêm Vương",

    # Các thần thoại
    # Aries
    "thần thoại về bạch dương": "Myth Aries", "thần thoại bạch dương": "Myth Aries", "thần thoại cừu vàng": "Myth Aries", "thần thoại con cừu vàng": "Myth Aries",
    "thần thoại aries": "Myth Aries", "câu chuyện aries": "Myth Aries", "thần thoại về aries": "Myth Aries", "thần thoại của aries": "Myth Aries",
    "câu chuyện về aries": "Myth Aries", "câu chuyện về cừu vàng": "Myth Aries", "câu chuyện về con cừu vàng": "Myth Aries", "câu chuyện về bạch dương": "Myth Aries",
    "câu chuyện về chòm sao bạch dương": "Myth Aries", "câu chuyện về chòm bạch dương": "Myth Aries", "thần thoại về chòm sao bạch dương": "Myth Aries", "thần thoại về chòm bạch dương": "Myth Aries",
    "thần thoại chòm sao bạch dương": "Myth Aries", "thần thoại chòm bạch dương": "Myth Aries",
    # Taurus
    "thần thoại về kim ngưu": "Myth Taurus", "thần thoại con bò mộng": "Myth Taurus", "thần thoại bò mộng": "Myth Taurus", "thần thoại bò mộng trắng": "Myth Taurus",
    "thần thoại taurus": "Myth Taurus", "câu chuyện taurus": "Myth Taurus", "thần thoại về taurus": "Myth Taurus", "thần thoại của taurus": "Myth Taurus",
    "câu chuyện về kim ngưu": "Myth Taurus", "câu chuyện về con bò": "Myth Taurus", "câu chuyện về bò mộng": "Myth Taurus", "câu chuyện về kim ngưu": "Myth Taurus",
    "câu chuyện về chòm sao kim ngưu": "Myth Taurus", "câu chuyện về chòm kim ngưu": "Myth Taurus", "thần thoại về chòm sao kim ngưu": "Myth Taurus", "thần thoại về chòm kim ngưu": "Myth Taurus",
    "thần thoại chòm sao kim ngưu": "Myth Taurus", "thần thoại chòm kim ngưu": "Myth Taurus",
    # Gemini
    "thần thoại về song tử": "Myth Gemini", "thần thoại song tử": "Myth Gemini", "thần thoại song sinh": "Myth Gemini", "thần thoại cặp song sinh": "Myth Gemini",
    "thần thoại gemini": "Myth Gemini", "câu chuyện gemini": "Myth Gemini", "thần thoại về gemini": "Myth Gemini", "thần thoại của gemini": "Myth Gemini",
    "câu chuyện về song tử": "Myth Gemini", "câu chuyện về song sinh": "Myth Gemini", "câu chuyện về cặp đôi": "Myth Gemini", "câu chuyện về cặp song sinh": "Myth Gemini",
    "câu chuyện về chòm sao song tử": "Myth Gemini", "câu chuyện về chòm song tử": "Myth Gemini", "thần thoại về chòm sao song tử": "Myth Gemini", "thần thoại về chòm song tử": "Myth Gemini",
    "thần thoại chòm sao song tử": "Myth Gemini", "thần thoại chòm song tử": "Myth Gemini",
    # Cancer
    "thần thoại về cự giải": "Myth Cancer", "thần thoại con cua": "Myth Cancer", "thần thoại cua khổng lồ": "Myth Cancer", "thần thoại cua": "Myth Cancer",
    "thần thoại cancer": "Myth Cancer", "câu chuyện cancer": "Myth Cancer", "thần thoại về cancer": "Myth Cancer", "thần thoại của cancer": "Myth Cancer",
    "câu chuyện về cự giải": "Myth Cancer", "câu chuyện về con cua": "Myth Cancer", "câu chuyện về cua khổng lồ": "Myth Cancer", "câu chuyện về cua": "Myth Cancer",
    "câu chuyện về chòm sao cự giải": "Myth Cancer", "câu chuyện về chòm cự giải": "Myth Cancer", "thần thoại về chòm sao cự giải": "Myth Cancer", "thần thoại về chòm cự giải": "Myth Cancer",
    "thần thoại chòm sao cự giải": "Myth Cancer", "thần thoại chòm cự giải": "Myth Cancer",
    # Leo
    "thần thoại về sư tử": "Myth Leo", "thần thoại sư tử": "Myth Leo", "thần thoại sư tử nemean": "Myth Leo", "thần thoại con sư tử": "Myth Leo",
    "thần thoại leo": "Myth Leo", "câu chuyện leo": "Myth Leo", "thần thoại về leo": "Myth Leo", "thần thoại của leo": "Myth Leo",
    "câu chuyện về sư tử": "Myth Leo", "câu chuyện về sư tử nemean": "Myth Leo", "câu chuyện về con sư tử": "Myth Leo", 
    "câu chuyện về chòm sao sư tử": "Myth Leo", "câu chuyện về chòm sư tử": "Myth Leo", "thần thoại về chòm sao sư tử": "Myth Leo", "thần thoại về chòm sư tử": "Myth Leo",
    "thần thoại chòm sao sư tử": "Myth Leo", "thần thoại chòm sư tử": "Myth Leo",
    # Virgo
    "thần thoại về xử nữ": "Myth Virgo", "thần thoại xử nữ": "Myth Virgo", "thần thoại astraea": "Myth Virgo", "thần thoại nữ thần công lý": "Myth Virgo",
    "thần thoại virgo": "Myth Virgo", "câu chuyện virgo": "Myth Virgo", "thần thoại về virgo": "Myth Virgo", "thần thoại của virgo": "Myth Virgo",
    "câu chuyện về xử nữ": "Myth Virgo", "câu chuyện về astraea": "Myth Virgo", "câu chuyện về nữ thần công lý": "Myth Virgo", 
    "câu chuyện về chòm sao xử nữ": "Myth Virgo", "câu chuyện về chòm xử nữ": "Myth Virgo", "thần thoại về chòm sao xử nữ": "Myth Virgo", "thần thoại về chòm xử nữ": "Myth Virgo",
    "thần thoại chòm sao xử nữ": "Myth Virgo", "thần thoại chòm xử nữ": "Myth Virgo",
    # Libra
    "thần thoại về thiên bình": "Myth Libra", "thần thoại thiên bình": "Myth Libra", "thần thoại cán cân công lý": "Myth Libra", "thần thoại cái cân": "Myth Libra",
    "thần thoại libra": "Myth Libra", "câu chuyện libra": "Myth Libra", "thần thoại về libra": "Myth Libra", "thần thoại của libra": "Myth Libra",
    "câu chuyện về thiên bình": "Myth Libra", "câu chuyện về cán cân": "Myth Libra", "câu chuyện về cái cân": "Myth Libra",
    "câu chuyện về chòm sao thiên bình": "Myth Libra", "câu chuyện về chòm thiên bình": "Myth Libra", "thần thoại về chòm sao thiên bình": "Myth Libra", "thần thoại về chòm thiên bình": "Myth Libra",
    "thần thoại chòm sao thiên bình": "Myth Libra", "thần thoại chòm thiên bình": "Myth Libra",
    # Scorpius
    "thần thoại về bọ cạp": "Myth Scorpius", "thần thoại bọ cạp": "Myth Scorpius", "thần thoại scorpius": "Myth Scorpius", "thần thoại con bò cạp": "Myth Scorpius",
    "thần thoại scorpius": "Myth Scorpius", "câu chuyện scorpius": "Myth Scorpius", "thần thoại về scorpius": "Myth Scorpius", "thần thoại của scorpius": "Myth Scorpius",
    "câu chuyện về bọ cạp": "Myth Scorpius", "câu chuyện về scorpius": "Myth Scorpius", "câu chuyện về con bò cạp": "Myth Scorpius",
    "câu chuyện về chòm sao bọ cạp": "Myth Scorpius", "câu chuyện về chòm bọ cạp": "Myth Scorpius", "thần thoại về chòm sao bọ cạp": "Myth Scorpius", "thần thoại về chòm bọ cạp": "Myth Scorpius",
    "thần thoại chòm sao bọ cạp": "Myth Scorpius", "thần thoại chòm bọ cạp": "Myth Scorpius",
    # Sagittarius
    "thần thoại về nhân mã": "Myth Sagittarius", "thần thoại nhân mã": "Myth Sagittarius", "thần thoại chiron": "Myth Sagittarius", "thần thoại xạ thủ": "Myth Sagittarius",
    "thần thoại sagittarius": "Myth Sagittarius", "câu chuyện sagittarius": "Myth Sagittarius", "thần thoại về sagittarius": "Myth Sagittarius", "thần thoại của sagittarius": "Myth Sagittarius",
    "câu chuyện về nhân mã": "Myth Sagittarius", "câu chuyện về chiron": "Myth Sagittarius", "câu chuyện về xạ thủ": "Myth Sagittarius",
    "câu chuyện về chòm sao nhân mã": "Myth Sagittarius", "câu chuyện về chòm nhân mã": "Myth Sagittarius", "thần thoại về chòm sao nhân mã": "Myth Sagittarius", "thần thoại về chòm nhân mã": "Myth Sagittarius",
    "thần thoại chòm sao nhân mã": "Myth Sagittarius", "thần thoại chòm nhân mã": "Myth Sagittarius",
    # Capricorn
    "thần thoại về ma kết": "Myth Capricorn", "thần thoại ma kết": "Myth Capricorn", "thần thoại aegipan": "Myth Capricorn", "thần thoại dê biển": "Myth Capricorn",
    "thần thoại capricorn": "Myth Capricorn", "câu chuyện capricorn": "Myth Capricorn", "thần thoại về capricorn": "Myth Capricorn", "thần thoại của capricorn": "Myth Capricorn",
    "câu chuyện về ma kết": "Myth Capricorn", "câu chuyện về aegipan": "Myth Capricorn", "câu chuyện về dê biển": "Myth Capricorn",
    "câu chuyện về chòm sao ma kết": "Myth Capricorn", "câu chuyện về chòm ma kết": "Myth Capricorn", "thần thoại về chòm sao ma kết": "Myth Capricorn", "thần thoại về chòm ma kết": "Myth Capricorn",
    "thần thoại chòm sao ma kết": "Myth Capricorn", "thần thoại chòm ma kết": "Myth Capricorn",
    # Aquarius
    "thần thoại về bảo bình": "Myth Aquarius", "thần thoại bảo bình": "Myth Aquarius", "thần thoại ganymede": "Myth Aquarius", "thần thoại người rót rượu": "Myth Aquarius",
    "thần thoại aquarius": "Myth Aquarius", "câu chuyện aquarius": "Myth Aquarius", "thần thoại về aquarius": "Myth Aquarius", "thần thoại của aquarius": "Myth Aquarius",
    "câu chuyện về bảo bình": "Myth Aquarius", "câu chuyện về ganymede": "Myth Aquarius", "câu chuyện về người rót rượu": "Myth Aquarius",
    "câu chuyện về chòm sao bảo bình": "Myth Aquarius", "câu chuyện về chòm bảo bình": "Myth Aquarius", "thần thoại về chòm sao bảo bình": "Myth Aquarius", "thần thoại về chòm bảo bình": "Myth Aquarius",
    "thần thoại chòm sao bảo bình": "Myth Aquarius", "thần thoại chòm bảo bình": "Myth Aquarius",
    # Pisces
    "thần thoại về song ngư": "Myth Pisces", "thần thoại song ngư": "Myth Pisces", "thần thoại ichthyes": "Myth Pisces", "thần thoại hai con cá": "Myth Pisces",
    "thần thoại pisces": "Myth Pisces", "câu chuyện pisces": "Myth Pisces", "thần thoại về pisces": "Myth Pisces", "thần thoại của pisces": "Myth Pisces",
    "câu chuyện về song ngư": "Myth Pisces", "câu chuyện về hai con cá": "Myth Pisces", "câu chuyện về aphrodite": "Myth Pisces",
    "câu chuyện về eros": "Myth Pisces", "câu chuyện về chòm sao song ngư": "Myth Pisces", "câu chuyện về chòm song ngư": "Myth Pisces", "thần thoại về chòm sao song ngư": "Myth Pisces", "thần thoại về chòm song ngư": "Myth Pisces",
    "thần thoại chòm sao song ngư": "Myth Pisces", "thần thoại chòm song ngư": "Myth Pisces",
}

# Mapping từ câu hỏi tự nhiên sang Thuộc tính/Quan hệ trong JSON (Intent Classification)
ATTRIBUTE_MAPPING = {
    # Quan hệ (Relations)
    "thuộc chòm sao": "Có_sao_sáng_nhất",
    "nằm trong chòm": "Có_sao_sáng_nhất",
    "sao sáng nhất": "Có_sao_sáng_nhất",
    "đại diện": "Đại_diện_cho",
    "biểu tượng": "Đại_diện_cho",
    "nguyên tố của": "Thuộc_Nguyên_tố",
    "thuộc nguyên tố": "Thuộc_Nguyên_tố",
    "có nguyên tố": "Thuộc_Nguyên_tố",
    "hệ nguyên tố": "Thuộc_Nguyên_tố",
    "cai quản": "Được_chi_phối",
    "chi phối": "Được_chi_phối",
    "có hành tinh chi phối": "Được_chi_phối",
    "hành tinh chi phối": "Được_chi_phối",
    "thuộc về hành tinh": "Được_chi_phối",
    "sao chiếu mệnh": "Được_chi_phối",
    "thần thoại": "Câu_chuyện",
    "truyền thuyết": "Câu_chuyện",
    "câu chuyện": "Câu_chuyện",
    "nguồn gốc": "Câu_chuyện",
    "chuyện": "Câu_chuyện",
    "truyện": "Câu_chuyện",
    "thực thể liên quan": "Thực_thể_liên_quan",
    
    # Thuộc tính (Concepts)
    "tên Việt": "Tên_Việt",
    "tên tiếng việt": "Tên_Việt",
    "tên tiếng việt của": "Tên_Việt",
    "tên việt": "Tên_Việt",
    "tên Latin": "Tên_Latin",
    "tên tiếng anh": "Tên_Anh",
    "tên quốc tế": "Tên_Anh",
    "tên anh": "Tên_Anh",
    "tên latin": "Tên_Latin",
    "tên la tinh": "Tên_Latin",
    "tên khoa học": "Tên_Latin",
    "tên của chòm sao": "Tên_Latin",
    "tên chòm sao": "Tên_Latin",
    "ký tự": "Ký_hiệu",
    "ký hiệu": "Ký_hiệu",
    "biểu tượng ký hiệu": "Ký_hiệu",
    "ngày mặt trời đi qua": "Thời_gian_mặt_trời_đi_qua",
    "thời gian mặt trời đi qua": "Thời_gian_mặt_trời_đi_qua",
    "thời gian mặt trời qua": "Thời_gian_mặt_trời_đi_qua",
    "mặt trời qua": "Thời_gian_mặt_trời_đi_qua",
    "mặt trời đi qua": "Thời_gian_mặt_trời_đi_qua",
    "mặt trời bắt đầu đi qua": "Thời_gian_mặt_trời_bắt_đầu",
    "ngày mặt trời bắt đầu": "Thời_gian_mặt_trời_bắt_đầu",
    "ngày mặt trời kết thúc": "Thời_gian_mặt_trời_kết_thúc",
    "thời gian sinh": "Thời_gian_sinh",
    "ngày sinh": "Thời_gian_sinh",
    "sinh nhật": "Thời_gian_sinh",
    "thời gian sinh bắt đầu": "Thời_gian_sinh_bắt_đầu",
    "ngày bắt đầu": "Thời_gian_sinh_bắt_đầu",
    "ngày sinh bắt đầu": "Thời_gian_sinh_bắt_đầu",
    "sinh ngày nào": "Thời_gian_sinh_bắt_đầu",  # Gần đúng
    "ngày kết thúc": "Thời_gian_sinh_kết_thúc",
    "ngày sinh kết thúc": "Thời_gian_sinh_kết_thúc",
    "thời gian sinh kết thúc": "Thời_gian_sinh_kết_thúc",
    "sinh sớm hơn": "Thời_gian_sinh_bắt_đầu",
    "sinh sớm nhất": "Thời_gian_sinh_bắt_đầu",
    "sinh muộn hơn": "Thời_gian_sinh_bắt_đầu",
    "sinh muộn nhất": "Thời_gian_sinh_bắt_đầu",
    "tóm tắt": "Tóm_tắt_TT",
    "tóm tắt thần thoại": "Tóm_tắt_TT",
    "mô tả": "Tóm_tắt_TT",
    "thông tin": "Tóm_tắt_TT",
    "đặc trưng của nguyên tố": "Đặc_trưng_nguyên_tố",
    "đặc trưng nguyên tố": "Đặc_trưng_nguyên_tố",
    "tính chất nguyên tố": "Đặc_trưng_nguyên_tố",
    "tính chất của nguyên tố": "Đặc_trưng_nguyên_tố",
    "đặc tính nguyên tố": "Đặc_trưng_nguyên_tố",
    "đặc tính của nguyên tố": "Đặc_trưng_nguyên_tố",
    "nguyên tố nào có đặc trưng": "Đặc_trưng_nguyên_tố",
    "nguyên tố có đặc trưng": "Đặc_trưng_nguyên_tố",
    "đặc trưng của hành tinh": "Đặc_trưng_hành_tinh",
    "đặc trưng sao": "Đặc_trưng_hành_tinh",
    "đặc trưng mặt trời": "Đặc_trưng_hành_tinh",
    "đăc trưng của mặt trời": "Đặc_trưng_hành_tinh",
    "mặt trời có đặc trưng": "Đặc_trưng_hành_tinh",
    "đặc trưng mặt trăng": "Đặc_trưng_hành_tinh",
    "đặc trưng của mặt trăng": "Đặc_trưng_hành_tinh",
    "mặt trăng có đặc trưng": "Đặc_trưng_hành_tinh",
    "đặc trưng của sao": "Đặc_trưng_hành_tinh",
    "đặc trưng hành tinh": "Đặc_trưng_hành_tinh",
    "tính chất hành tinh": "Đặc_trưng_hành_tinh",
    "tính chất của hành tinh": "Đặc_trưng_hành_tinh",
    "hành tinh có đặc trưng": "Đặc_trưng_hành_tinh",
    "hành tinh nào có đặc trưng": "Đặc_trưng_hành_tinh",
    "cấp sao": "Cấp_sao",
    "độ sáng": "Cấp_sao",
    "sáng hơn": "Cấp_sao",
    "sao nào sáng": "Cấp sao",
    # "sáng nhất": "Cấp_sao",
    "mờ hơn": "Cấp_sao",
    "cấp sao biểu kiến": "Cấp_sao",
    "độ sáng biểu kiến": "Cấp_sao",
    "loại quang phổ": "Loại_quang_phổ",
    "quang phổ": "Loại_quang_phổ",
    "khoảng cách": "Khoảng_cách",
    "lớn hơn": "Khoảng_cách",
    "nhỏ hơn": "Khoảng_cách",
    "lớn hơn khoảng cách": "Khoảng_cách",
    "nhỏ hơn khoảng cách": "Khoảng_cách",
    "xa": "Khoảng_cách",
    "gần": "Khoảng_cách",
    "từ trái đất đến": "Khoảng_cách",
    "cách trái đất": "Khoảng_cách",
    "mô tả": "Mô_tả_thực_thể_TT",
    "là ai": "Mô_tả_thực_thể_TT",
    "là sinh vật": "Mô_tả_thực_thể_TT",
    "là thần": "Mô_tả_thực_thể_TT",
    "thuộc loại gì": "Instance_of",
    "thuộc nhóm gì": "Instance_of"
}
